version: '3.8'

services:
  server:
    container_name: Bro-code-server
    build:
      context: ./server
      dockerfile: Dockerfile
      target: runner
    volumes:
      - ./server:/app
      - /app/node_modules  # Mount node_modules inside container to prevent overwriting
    networks:
      - Bro-code
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  client:
    container_name: Bro-code-client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: runner
    volumes:
      - ./client:/app
      - /app/node_modules  # Mount node_modules inside container to prevent overwriting
    networks:
      - Bro-code
    ports:
      - "5173:5173"
    depends_on:
      - server
    environment:
      - NODE_ENV=production

networks:
  Bro-code:
    driver: bridge
