services:
  server:
    container_name: Bro-code-server
    build:
      context: ./server
      dockerfile: Dockerfile
      target: runner
    volumes:
      - ./server:/app
      - /build/node_modules
    networks:
      - Bro-code
    ports:
      - "3000:3000"

  client:
    container_name: Bro-code-client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: runner
    volumes:
      - ./client:/app
      - /build/node_modules
    networks:
      - Bro-code
    ports:
      - "5173:5173"
    depends_on:
      - server

networks:
  Bro-code:  # <--- fixed here
    driver: bridge
